version: "3.8"

services:
  postgres:
    container_name: identity-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity-db