@IdentityUser.Api_HostAddress = http://localhost:5227

POST {{IdentityUser.Api_HostAddress}}/api/User/login
Accept: application/json
Content-Type: application/json
{
  "UserName": "User1",
  "Password": "Senha123#"
}

###
